# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: C:\Users\timmo\Documents\GitHub\napari-plugin-template
display_name: ndev Batch
email: timmonko@gmail.com
full_name: Tim Monko
github_repository_url: https://github.com/ndev-kit/ndev-batch
github_username_or_organization: ndev-kit
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: false
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: ndev_batch
plugin_name: ndev-batch
short_description: Flexible batch processing utilities
